//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeLong_Desktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeLong_Desktop.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amallar.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qo‘shish.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijozlarni qo&apos;shish oynasi.
        /// </summary>
        internal static string AddClientWindow {
            get {
                return ResourceManager.GetString("AddClientWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qo&apos;shimcha amallar.
        /// </summary>
        internal static string AdditionalOperations {
            get {
                return ResourceManager.GetString("AdditionalOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manzil.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amallar.
        /// </summary>
        internal static string Amallar {
            get {
                return ResourceManager.GetString("Amallar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toifa.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chegirma.
        /// </summary>
        internal static string Chegirma {
            get {
                return ResourceManager.GetString("Chegirma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijoz FIO.
        /// </summary>
        internal static string ClientFullname {
            get {
                return ResourceManager.GetString("ClientFullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijoz.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delong.
        /// </summary>
        internal static string Delong {
            get {
                return ResourceManager.GetString("Delong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar.
        /// </summary>
        internal static string Dollar {
            get {
                return ResourceManager.GetString("Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ kursi.
        /// </summary>
        internal static string dollorkursi {
            get {
                return ResourceManager.GetString("dollorkursi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $kursini kiriting.
        /// </summary>
        internal static string dollorkursini_kiriting {
            get {
                return ResourceManager.GetString("dollorkursini kiriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duedata.
        /// </summary>
        internal static string DueData {
            get {
                return ResourceManager.GetString("DueData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiqish.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sotuv amallari.
        /// </summary>
        internal static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faolligi.
        /// </summary>
        internal static string Faolligi {
            get {
                return ResourceManager.GetString("Faolligi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirim.
        /// </summary>
        internal static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jami summa .
        /// </summary>
        internal static string Jami_summa_ {
            get {
                return ResourceManager.GetString("Jami summa ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSHSHIR.
        /// </summary>
        internal static string JSHSHIR {
            get {
                return ResourceManager.GetString("JSHSHIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriya .
        /// </summary>
        internal static string Kategoriya_ {
            get {
                return ResourceManager.GetString("Kategoriya ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulot nomi.
        /// </summary>
        internal static string Mahsulot_nomi {
            get {
                return ResourceManager.GetString("Mahsulot nomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulot nomi .
        /// </summary>
        internal static string Mahsulot_nomi_ {
            get {
                return ResourceManager.GetString("Mahsulot nomi ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulotni tanlang .
        /// </summary>
        internal static string Mahsulotni_tanlang_ {
            get {
                return ResourceManager.GetString("Mahsulotni tanlang ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijozlar .
        /// </summary>
        internal static string Mijozlar_ {
            get {
                return ResourceManager.GetString("Mijozlar ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijozni tanlang .
        /// </summary>
        internal static string Mijozni_tanlang_ {
            get {
                return ResourceManager.GetString("Mijozni tanlang ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miqdori.
        /// </summary>
        internal static string Miqdori {
            get {
                return ResourceManager.GetString("Miqdori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naqd.
        /// </summary>
        internal static string Naqd {
            get {
                return ResourceManager.GetString("Naqd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narxi.
        /// </summary>
        internal static string Narxi {
            get {
                return ResourceManager.GetString("Narxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O&apos;chirish.
        /// </summary>
        internal static string O_chirish {
            get {
                return ResourceManager.GetString("O\'chirish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O&apos;lchov birligi .
        /// </summary>
        internal static string O_lchov_birligi_ {
            get {
                return ResourceManager.GetString("O\'lchov birligi ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ombordagi miqdor .
        /// </summary>
        internal static string Ombordagi_miqdor_ {
            get {
                return ResourceManager.GetString("Ombordagi miqdor ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastik.
        /// </summary>
        internal static string Plastik {
            get {
                return ResourceManager.GetString("Plastik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulot.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qarz.
        /// </summary>
        internal static string Qarz {
            get {
                return ResourceManager.GetString("Qarz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hisobot.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sotuv tarixi.
        /// </summary>
        internal static string SaleHistory {
            get {
                return ResourceManager.GetString("SaleHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qidiruv.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sotib olish .
        /// </summary>
        internal static string Sotib_olish_ {
            get {
                return ResourceManager.GetString("Sotib olish ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sotish.
        /// </summary>
        internal static string Sotish {
            get {
                return ResourceManager.GetString("Sotish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sotuvni amalga oshirish.
        /// </summary>
        internal static string Sotuv {
            get {
                return ResourceManager.GetString("Sotuv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t/r.
        /// </summary>
        internal static string t_r {
            get {
                return ResourceManager.GetString("t/r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram raqami.
        /// </summary>
        internal static string Telegram_Phone_Number {
            get {
                return ResourceManager.GetString("Telegram Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To&apos;lov summasi .
        /// </summary>
        internal static string To_lov_summasi_ {
            get {
                return ResourceManager.GetString("To\'lov summasi ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellga o&apos;tkazish.
        /// </summary>
        internal static string ToExcell {
            get {
                return ResourceManager.GetString("ToExcell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umumiy summasi .
        /// </summary>
        internal static string Umumiy_summasi_ {
            get {
                return ResourceManager.GetString("Umumiy summasi ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valyutani ayirboshlash .
        /// </summary>
        internal static string Valyutani_ayirboshlash_ {
            get {
                return ResourceManager.GetString("Valyutani ayirboshlash ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ombor.
        /// </summary>
        internal static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakunlash.
        /// </summary>
        internal static string Yakunlash {
            get {
                return ResourceManager.GetString("Yakunlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakunlash .
        /// </summary>
        internal static string Yakunlash_ {
            get {
                return ResourceManager.GetString("Yakunlash ", resourceCulture);
            }
        }
    }
}
