//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeLong_Desktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeLong_Desktop.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amallar.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qo‘shish.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijozlarni qo&apos;shish oynasi.
        /// </summary>
        internal static string AddClientWindow {
            get {
                return ResourceManager.GetString("AddClientWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qo&apos;shimcha amallar.
        /// </summary>
        internal static string additionalActions {
            get {
                return ResourceManager.GetString("additionalActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qo&apos;shimcha amallar.
        /// </summary>
        internal static string AdditionalOperations {
            get {
                return ResourceManager.GetString("AdditionalOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manzil.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amallar .
        /// </summary>
        internal static string Amallar_ {
            get {
                return ResourceManager.GetString("Amallar ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summasi.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boshqa.
        /// </summary>
        internal static string Boshqa {
            get {
                return ResourceManager.GetString("Boshqa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filial.
        /// </summary>
        internal static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filial.
        /// </summary>
        internal static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastik.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassa.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toifa.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chegirma $ da.
        /// </summary>
        internal static string Chegirma_ {
            get {
                return ResourceManager.GetString("Chegirma ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chek Id.
        /// </summary>
        internal static string Chek_Id {
            get {
                return ResourceManager.GetString("Chek Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izoh.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasdiqlash.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulot tannarxi.
        /// </summary>
        internal static string CostPrice {
            get {
                return ResourceManager.GetString("CostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar.
        /// </summary>
        internal static string Currency_Dollar_ {
            get {
                return ResourceManager.GetString("Currency_Dollar ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastik.
        /// </summary>
        internal static string Currency_Plastic_ {
            get {
                return ResourceManager.GetString("Currency_Plastic ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So&apos;m.
        /// </summary>
        internal static string Currency_Sum {
            get {
                return ResourceManager.GetString("Currency_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijoz.
        /// </summary>
        internal static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijoz nomi.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijoz.
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qarz summasi.
        /// </summary>
        internal static string DebtAmount {
            get {
                return ResourceManager.GetString("DebtAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O&apos;chirish.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar.
        /// </summary>
        internal static string Dollar {
            get {
                return ResourceManager.GetString("Dollar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar kursi .
        /// </summary>
        internal static string Dollar_kursi_ {
            get {
                return ResourceManager.GetString("Dollar kursi ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar kursini kiriting .
        /// </summary>
        internal static string Dollar_kursini_kiriting_ {
            get {
                return ResourceManager.GetString("Dollar kursini kiriting ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DueData .
        /// </summary>
        internal static string DueData_ {
            get {
                return ResourceManager.GetString("DueData ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodim FIO.
        /// </summary>
        internal static string EmployeeFullname {
            get {
                return ResourceManager.GetString("EmployeeFullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string EmployeePhone {
            get {
                return ResourceManager.GetString("EmployeePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodim.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiqish.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sotuv amallari.
        /// </summary>
        internal static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faolligi .
        /// </summary>
        internal static string Faolligi_ {
            get {
                return ResourceManager.GetString("Faolligi ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirim tarixi.
        /// </summary>
        internal static string HistoryInput {
            get {
                return ResourceManager.GetString("HistoryInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirim.
        /// </summary>
        internal static string Incoming {
            get {
                return ResourceManager.GetString("Incoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izoh.
        /// </summary>
        internal static string Izoh {
            get {
                return ResourceManager.GetString("Izoh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jami qarz.
        /// </summary>
        internal static string Jami_qarz {
            get {
                return ResourceManager.GetString("Jami qarz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jami summa $ da.
        /// </summary>
        internal static string Jami_summa_ {
            get {
                return ResourceManager.GetString("Jami summa ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSHSHIR.
        /// </summary>
        internal static string JSHSHIR {
            get {
                return ResourceManager.GetString("JSHSHIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassa aylanmasi.
        /// </summary>
        internal static string Kassa_aylanmasi {
            get {
                return ResourceManager.GetString("Kassa aylanmasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassa o&apos;tkazmalari.
        /// </summary>
        internal static string Kassa_o_tkazmalari {
            get {
                return ResourceManager.GetString("Kassa o\'tkazmalari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassadan.
        /// </summary>
        internal static string Kassadan {
            get {
                return ResourceManager.GetString("Kassadan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassaga.
        /// </summary>
        internal static string Kassaga {
            get {
                return ResourceManager.GetString("Kassaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassani boshqarish.
        /// </summary>
        internal static string Kassani_boshqarish {
            get {
                return ResourceManager.GetString("Kassani boshqarish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriya.
        /// </summary>
        internal static string Kategoriya {
            get {
                return ResourceManager.GetString("Kategoriya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriya bo&apos;yicha qidiruv.
        /// </summary>
        internal static string kategoriya_boyicha_qidiruv {
            get {
                return ResourceManager.GetString("kategoriya boyicha qidiruv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimdan qaytmoqda.
        /// </summary>
        internal static string Kimdan_qaytmoqda {
            get {
                return ResourceManager.GetString("Kimdan qaytmoqda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunni ochish.
        /// </summary>
        internal static string Kunni_ochish {
            get {
                return ResourceManager.GetString("Kunni ochish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillar.
        /// </summary>
        internal static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulot nomi .
        /// </summary>
        internal static string Mahsulot_nomi_ {
            get {
                return ResourceManager.GetString("Mahsulot nomi ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulot tannarxi.
        /// </summary>
        internal static string Mahsulot_tannarxi {
            get {
                return ResourceManager.GetString("Mahsulot tannarxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulotni qidirish .
        /// </summary>
        internal static string Mahsulotni_qidirish_ {
            get {
                return ResourceManager.GetString("Mahsulotni qidirish ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulotni tanlang .
        /// </summary>
        internal static string Mahsulotni_tanlang_ {
            get {
                return ResourceManager.GetString("Mahsulotni tanlang ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rahbar FIO.
        /// </summary>
        internal static string ManagerFullName {
            get {
                return ResourceManager.GetString("ManagerFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijoz nomi.
        /// </summary>
        internal static string Mijoz_nomi {
            get {
                return ResourceManager.GetString("Mijoz nomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijozlar.
        /// </summary>
        internal static string Mijozlar {
            get {
                return ResourceManager.GetString("Mijozlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijozni tanlang.
        /// </summary>
        internal static string Mijozni_tanlang_ {
            get {
                return ResourceManager.GetString("Mijozni_tanlang_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miqdori.
        /// </summary>
        internal static string Miqdori_ {
            get {
                return ResourceManager.GetString("Miqdori_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naqd .
        /// </summary>
        internal static string Naqd_ {
            get {
                return ResourceManager.GetString("Naqd ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narxi .
        /// </summary>
        internal static string Narxi_ {
            get {
                return ResourceManager.GetString("Narxi ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O&apos;tkazish.
        /// </summary>
        internal static string O_tkazish {
            get {
                return ResourceManager.GetString("O\'tkazish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O&apos;chirish.
        /// </summary>
        internal static string Ochirish {
            get {
                return ResourceManager.GetString("Ochirish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olchov birligi.
        /// </summary>
        internal static string Olchov_birligi {
            get {
                return ResourceManager.GetString("Olchov birligi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ombor mudiri .
        /// </summary>
        internal static string Ombor_mudiri_ {
            get {
                return ResourceManager.GetString("Ombor mudiri ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ombor nomi .
        /// </summary>
        internal static string Ombor_nomi_ {
            get {
                return ResourceManager.GetString("Ombor nomi ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulot qoldiq.
        /// </summary>
        internal static string Ombordagi_miqdor_ {
            get {
                return ResourceManager.GetString("Ombordagi miqdor ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omborlar ortasida otkazmalar.
        /// </summary>
        internal static string Omborlar_ortasida_otkazmalar {
            get {
                return ResourceManager.GetString("Omborlar ortasida otkazmalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To&apos;lash.
        /// </summary>
        internal static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qarzni to‘lash.
        /// </summary>
        internal static string PayDebt {
            get {
                return ResourceManager.GetString("PayDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pechat.
        /// </summary>
        internal static string Pechat {
            get {
                return ResourceManager.GetString("Pechat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastik .
        /// </summary>
        internal static string Plastik_ {
            get {
                return ResourceManager.GetString("Plastik ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulot.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulotlar ro&apos;yxati.
        /// </summary>
        internal static string ProductList {
            get {
                return ResourceManager.GetString("ProductList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulot nomi.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulotlar.
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulot belgisi.
        /// </summary>
        internal static string ProductSign {
            get {
                return ResourceManager.GetString("ProductSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qarz $ da.
        /// </summary>
        internal static string Qarz {
            get {
                return ResourceManager.GetString("Qarz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qarz summasi.
        /// </summary>
        internal static string Qarz_summasi {
            get {
                return ResourceManager.GetString("Qarz summasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qarzni tolash.
        /// </summary>
        internal static string Qarzni_tolash {
            get {
                return ResourceManager.GetString("Qarzni tolash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qaysi omborga.
        /// </summary>
        internal static string Qaysi_omborga {
            get {
                return ResourceManager.GetString("Qaysi omborga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qaytgan mahsulotlar.
        /// </summary>
        internal static string Qaytgan_mahsulotlar {
            get {
                return ResourceManager.GetString("Qaytgan mahsulotlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qoshimcha amallar.
        /// </summary>
        internal static string Qoshimcha_amallar {
            get {
                return ResourceManager.GetString("Qoshimcha amallar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miqdori.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chek Id.
        /// </summary>
        internal static string ReceiptId {
            get {
                return ResourceManager.GetString("ReceiptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hisobot.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kimda qatmoqda.
        /// </summary>
        internal static string ReturnedFrom {
            get {
                return ResourceManager.GetString("ReturnedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qaytgan mahsulotlar.
        /// </summary>
        internal static string ReturnedProducts {
            get {
                return ResourceManager.GetString("ReturnedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sotuv tarixi.
        /// </summary>
        internal static string SaleHistory {
            get {
                return ResourceManager.GetString("SaleHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sotuv.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sotuv tarixi.
        /// </summary>
        internal static string SalesHistory {
            get {
                return ResourceManager.GetString("SalesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sotuv amallar.
        /// </summary>
        internal static string SalesOperations {
            get {
                return ResourceManager.GetString("SalesOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sana.
        /// </summary>
        internal static string Sana {
            get {
                return ResourceManager.GetString("Sana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qidiruv.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulot tanlang.
        /// </summary>
        internal static string SelectProduct {
            get {
                return ResourceManager.GetString("SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jo&apos;natish.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sozlash.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sotib olish .
        /// </summary>
        internal static string Sotib_olish_ {
            get {
                return ResourceManager.GetString("Sotib olish ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sotish .
        /// </summary>
        internal static string Sotish_ {
            get {
                return ResourceManager.GetString("Sotish ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sotuvlar tarixi.
        /// </summary>
        internal static string Sotuvlar_tarixi {
            get {
                return ResourceManager.GetString("Sotuvlar tarixi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sotuvni amalga oshirish .
        /// </summary>
        internal static string Sotuvni_amalga_oshirish_ {
            get {
                return ResourceManager.GetString("Sotuvni amalga oshirish ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taminotchi.
        /// </summary>
        internal static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T/r .
        /// </summary>
        internal static string T_r_ {
            get {
                return ResourceManager.GetString("T/r ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram raqami.
        /// </summary>
        internal static string Telegram_Phone_Number {
            get {
                return ResourceManager.GetString("Telegram Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellga o&apos;tkazish.
        /// </summary>
        internal static string ToExcell {
            get {
                return ResourceManager.GetString("ToExcell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To&apos;lash.
        /// </summary>
        internal static string Tolash {
            get {
                return ResourceManager.GetString("Tolash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To&apos;lash muddati.
        /// </summary>
        internal static string Tolash_muddati {
            get {
                return ResourceManager.GetString("Tolash muddati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To&apos;lov summasi $ da.
        /// </summary>
        internal static string Tolovsummasi {
            get {
                return ResourceManager.GetString("Tolovsummasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umumiy summa.
        /// </summary>
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jami qarz.
        /// </summary>
        internal static string TotalDebt {
            get {
                return ResourceManager.GetString("TotalDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qaysi omborga.
        /// </summary>
        internal static string ToWarehouse {
            get {
                return ResourceManager.GetString("ToWarehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaksiya turi.
        /// </summary>
        internal static string TransactionType {
            get {
                return ResourceManager.GetString("TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umumiy summasi .
        /// </summary>
        internal static string Umumiy_summasi_ {
            get {
                return ResourceManager.GetString("Umumiy summasi ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O&apos;lchov birligi.
        /// </summary>
        internal static string UnitOfMeasure {
            get {
                return ResourceManager.GetString("UnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foydalanuvchi.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valyutani ayirboshlash .
        /// </summary>
        internal static string Valyutani_ayirboshlash_ {
            get {
                return ResourceManager.GetString("Valyutani ayirboshlash ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omborlar o‘rtasida o&apos;tkazmalar.
        /// </summary>
        internal static string WarehouseTransfer {
            get {
                return ResourceManager.GetString("WarehouseTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yakunlash .
        /// </summary>
        internal static string Yakunlash_ {
            get {
                return ResourceManager.GetString("Yakunlash ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaxiradagi pullar.
        /// </summary>
        internal static string Zaxiradagi_pullar {
            get {
                return ResourceManager.GetString("Zaxiradagi_pullar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaxiradan.
        /// </summary>
        internal static string Zaxiradan {
            get {
                return ResourceManager.GetString("Zaxiradan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaxiraga.
        /// </summary>
        internal static string Zaxiraga {
            get {
                return ResourceManager.GetString("Zaxiraga", resourceCulture);
            }
        }
    }
}
